// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dogcollar.proto

package dogcollar

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Activity struct {
	Timestamp               *uint64  `protobuf:"varint,1,req,name=timestamp" json:"timestamp,omitempty"`
	SerializedRoaringBitmap []byte   `protobuf:"bytes,2,req,name=serialized_roaring_bitmap,json=serializedRoaringBitmap" json:"serialized_roaring_bitmap,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *Activity) Reset()         { *m = Activity{} }
func (m *Activity) String() string { return proto.CompactTextString(m) }
func (*Activity) ProtoMessage()    {}
func (*Activity) Descriptor() ([]byte, []int) {
	return fileDescriptor_be2db778eba52e35, []int{0}
}

func (m *Activity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Activity.Unmarshal(m, b)
}
func (m *Activity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Activity.Marshal(b, m, deterministic)
}
func (m *Activity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Activity.Merge(m, src)
}
func (m *Activity) XXX_Size() int {
	return xxx_messageInfo_Activity.Size(m)
}
func (m *Activity) XXX_DiscardUnknown() {
	xxx_messageInfo_Activity.DiscardUnknown(m)
}

var xxx_messageInfo_Activity proto.InternalMessageInfo

func (m *Activity) GetTimestamp() uint64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *Activity) GetSerializedRoaringBitmap() []byte {
	if m != nil {
		return m.SerializedRoaringBitmap
	}
	return nil
}

func init() {
	proto.RegisterType((*Activity)(nil), "Activity")
}

func init() { proto.RegisterFile("dogcollar.proto", fileDescriptor_be2db778eba52e35) }

var fileDescriptor_be2db778eba52e35 = []byte{
	// 120 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0xc9, 0x4f, 0x4f,
	0xce, 0xcf, 0xc9, 0x49, 0x2c, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x4a, 0xe1, 0xe2, 0x70,
	0x4c, 0x2e, 0xc9, 0x2c, 0xcb, 0x2c, 0xa9, 0x14, 0x92, 0xe1, 0xe2, 0x2c, 0xc9, 0xcc, 0x4d, 0x2d,
	0x2e, 0x49, 0xcc, 0x2d, 0x90, 0x60, 0x54, 0x60, 0xd2, 0x60, 0x09, 0x42, 0x08, 0x08, 0x59, 0x71,
	0x49, 0x16, 0xa7, 0x16, 0x65, 0x26, 0xe6, 0x64, 0x56, 0xa5, 0xa6, 0xc4, 0x17, 0xe5, 0x27, 0x16,
	0x65, 0xe6, 0xa5, 0xc7, 0x27, 0x65, 0x96, 0xe4, 0x26, 0x16, 0x48, 0x30, 0x29, 0x30, 0x69, 0xf0,
	0x04, 0x89, 0x23, 0x14, 0x04, 0x41, 0xe4, 0x9d, 0xc0, 0xd2, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x3b, 0xfc, 0x1a, 0x2d, 0x77, 0x00, 0x00, 0x00,
}
